### ISSUE TITLE
PCL2启动提示Minecraft出现错误

### ISSUE THREAD

**Issue by aboluo12138** [Fndream/BorderSurvivalModpack#2]
弹窗提示“名为Sodium的Mod可能导致了游戏错误”
因为我没有mod百科的账号，所以我只能来着反馈了
![图片](https://github.com/Fndream/BorderSurvivalModpack/assets/38574949/43e54cd4-5a18-4436-ba68-b1da4f505710)
[错误报告-2024-2-22_12.31.06.zip](https://github.com/Fndream/BorderSurvivalModpack/files/14368883/-2024-2-22_12.31.06.zip)

**Comment by Fndream** [comment]
实在抱歉，我的邮箱最近几个月频繁收到来自微软的推送，一直没放在心上去解决，导致该issues被这些推送刷过去了，没有第一时间看到，我刚刚过来github才发现你提出的此issues。

最新版本8.4.2应该没问题。

_防止以后再出现此类问题，我会立刻前去研究解决微软推送的问题。_

_已解决，是由于微软账户默认开启通信订阅。_
