### ISSUE TITLE
请问支持服务器联机吗

### ISSUE THREAD

**Issue by littzhch** [Fndream/BorderSurvivalModpack#3]
如果支持的话，服务器需要安装哪些mod，需要特殊的配置吗？

**Comment by Fndream** [comment]
支持的，目前这个包，准确说是边界模组，只支持1.20.4。在服务器上安装一个1.20.4的fabric服务端，然后将整合包里的mods文件夹不用管客户端还是服务端模组，一股脑全丢进服务端的mods文件夹中就行。然后需要将地图包解压，改名为world，也就是让服务器加载边界的地图。
